# TODO: Allow building both Note 10 Lite and S9

# dtbo-y += samsung/exynos9810-r7_eur_open_01.dtbo
# dtbo-y += samsung/exynos9810-r7_eur_open_03.dtbo
# dtbo-y += samsung/exynos9810-r7_eur_open_04.dtbo
# dtbo-y += samsung/exynos9810-r7_eur_open_00.dtbo
# dtbo-y += samsung/exynos9810-r7_eur_open_05.dtbo
# dtbo-y += samsung/exynos9810-r7_eur_open_02.dtbo
